// src/core/commands/todo/TodoBox.tsx
import { TodoStore } from '@/stores';
import MyDayjs from '@/utils/myDayjs';
import { Button, Card, Checkbox, List } from 'antd';
import React from 'react';
interface TodoBoxProps {
  today: boolean;
}

const ToDoBox: React.FC<TodoBoxProps> = ({ today }) => {
  const {
    taskList,
    deleteTask,
  }: { taskList: Todo.TaskType[]; deleteTask: (id: number) => void } =
    TodoStore();

  const doDelete = (index: number) => {
    deleteTask(index);
  };
  return (
    <div style={{ margin: '8px 0', maxWidth: '600px' }}>
      <Card styles={{ body: { padding: '0 12px' } }}>
        <List itemLayout="vertical">
          {taskList.map((item, index) => {
            return (
              <List.Item
                key={index}
                actions={[
                  <Button
                    key={index}
                    type="text"
                    danger
                    onClick={() => doDelete(index)}
                  >
                    删除
                  </Button>,
                ]}
              >
                <List.Item.Meta
                  title={item.name}
                  description={`创建时间：${MyDayjs(item.createTime).format(
                    'YYYY-MM-DD HH:mm:ss',
                  )}`}
                  avatar={<Checkbox checked={item.isFinished} />}
                />
              </List.Item>
            );
          })}
        </List>
      </Card>
    </div>
  );
};

export default ToDoBox;

// src/core/commands/todo/TodoBox.vue
<template>
  <div style="margin: 8px 0; max-width: 600px">
    <a-card body-style="padding: 0 12px">
      <a-list item-layout="horizontal" :data-source="taskList">
        <template #renderItem="{ item, index }">
          <a-list-item>
            <template #actions>
              <a-button type="text" danger @click="doDelete(index)"
                >删除
              </a-button>
            </template>
            <a-list-item-meta>
              <template #title>
                {{ item.name }}
              </template>
              <template #description>
                创建时间：{{
                  MyDayjs(item.createTime).format('YYYY-MM-DD HH:mm:ss')
                }}
              </template>
              <template #avatar>
                <a-checkbox v-model:checked="item.isFinished" />
              </template>
            </a-list-item-meta>
          </a-list-item>
        </template>
      </a-list>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { toRefs } from 'vue';
import { TodoStore } from '@/stores';
import MyDayjs from '../../../plugins/myDayjs';

interface TodoBoxProps {
  today: boolean;
}

const props = withDefaults(defineProps<TodoBoxProps>(), {});
const { today } = toRefs(props);

const { taskList, deleteTask } = TodoStore();

const doDelete = (index: number) => {
  deleteTask(index);
};
</script>

<style scoped></style>
