// src/core/commands/varbook/VarbookBox.vue
<!-- <template>
  <div :class="['main', variablesTable.source ? 'success' : 'warning']">
    <a-spin
      :spinning="!loadOK"
      :style="{
        height: !loadOK ? '283px' : '',
        position: !loadOK ? 'inherit' : '',
      }"
    >
      <div v-show="loadOK">
        <a-table
          v-if="variablesTable?.source"
          class="table"
          :data-source="variablesTable?.source"
          :columns="variablesTable?.columns"
          :size="'small'"
          :pagination="false"
        />
        <content-output v-else :output="output" />
      </div>
    </a-spin>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, toRefs } from 'vue';
import { getNamedVariables } from '@/api/translate';
import { parseNamedVariable } from './standard';
import ContentOutput from '@/components/yu-terminal/ContentOutput.vue';
import OutputType = Terminal.OutputType;

interface VariableBoxProps {
  searchText: string;
}

const props = defineProps<VariableBoxProps>();

const { searchText } = toRefs(props);
const variablesTable = ref<any>({});
const loadOK = ref(false);
const output = reactive<OutputType>({
  type: 'text',
  status: 'warning',
  text: '',
});

getNamedVariables(searchText.value)
  .then((res: any) => {
    const { code, data, msg } = res;
    code === 200
      ? (variablesTable.value = parseNamedVariable(data.namedVariables))
      : (output.text = msg);
  })
  .catch((err: any) => {
    output.text = '服务器扛不住了，请稍后再试';
  })
  .finally(() => {
    loadOK.value = true;
  });
</script>

<style scoped>
.main {
  max-width: 600px;
}

.success {
  margin: 8px 0;
}

.warning {
  margin: 0;
}

.table {
  overflow: hidden;
  background-color: white;
  padding: 5px;
  border-radius: 10px;
  box-shadow: 2px 3px 3px 1px #8b8b8b59;
}
</style>
./hooks/api/translate ../../../api/translate ./standard/standard -->

// src/core/commands/varbook/VarbookBox.tsx
import { getNamedVariables } from '@/api/translate';
import ContentOutput from '@/components/ContentOutput';
import { Spin, Table } from 'antd';
import React, { useEffect, useState } from 'react';
import './VarbookBox.less';
import { parseNamedVariable } from './standard';

interface VariableBoxProps {
  searchText: string;
}

export const VarbookBox: React.FC<VariableBoxProps> = ({ searchText }) => {
  const [variablesTable, setVariablesTable] = useState<any>({});
  const [loadOK, setLoadOK] = useState(false);
  const [output, setOutput] = useState<Terminal.OutputType>({
    type: 'text',
    status: 'warning',
    text: '',
  });

  useEffect(() => {
    getNamedVariables(searchText)
      .then((res: any) => {
        const { code, data, msg } = res;
        if (code === 200) {
          setVariablesTable(parseNamedVariable(data.namedVariables));
        } else {
          setOutput({ type: 'text', status: 'error', text: msg });
        }
      })
      .catch((err: any) => {
        output.text = '服务器扛不住了，请稍后再试';
        console.log(err);
      })
      .finally(() => {
        setLoadOK(true);
      });
  }, []);

  return (
    <div className={`main ${variablesTable.source ? 'success' : 'warning'}`}>
      <Spin
        spinning={!loadOK}
        style={{
          height: !loadOK ? '283px' : '',
          // position: !loadOK ? 'inherit' : '',
        }}
      >
        {loadOK && (
          <div>
            <Table
              className="table"
              size="small"
              dataSource={variablesTable?.source}
              columns={variablesTable?.columns}
              pagination={false}
            ></Table>
            <ContentOutput output={output} />
          </div>
        )}
      </Spin>
    </div>
  );
};
